name: Create Article

on:
  schedule:
    - cron: "0 21 * * *" # JST 06:00
    - cron: "0 9 * * *" # JST 18:00
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create-article:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sandbox
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          working_directory: sandbox
      - run: npm clean-install
      - run: npx tsx server/batch/create-article.ts
        env:
          DB_FILE_NAME: ${{ secrets.DB_FILE_NAME }}
