name: Deploy Application

on:
  push:
    branches:
      - main
    paths:
      - sandbox/**
      - .github/workflows/deploy-application.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  migrate-database:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sandbox
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          working_directory: sandbox
      - run: npm clean-install
      - run: npx drizzle-kit migrate
        env:
          DB_FILE_NAME: ${{ secrets.DB_FILE_NAME }}

  deploy-application:
    needs: migrate-database
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sandbox
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          working_directory: sandbox
      - run: npm clean-install
      - run: npx vercel pull -y --environment production -t ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      - run: npx vercel build --prod -t ${{ secrets.VERCEL_TOKEN }}
        env:
          NITRO_PRESET: vercel
          VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      - run: npx vercel deploy --prebuilt --prod -t ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
