name: Seed Database

on:
  workflow_dispatch:

jobs:
  seed-database:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sandbox
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          working_directory: sandbox
      - run: npm clean-install
      - run: npx tsx server/db/seed/index.ts
        env:
          DB_FILE_NAME: ${{ secrets.DB_FILE_NAME }}
